# Setup
title:               YKarroum
tagline:             'A blog about python, finance and other stuffs'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://ykarroum.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yassir Karroum
  url:               http://ykarroum.com
  email:             ukarroum17@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
