# Setup
title:               YKarroum
#tagline:             'Another personal blog'
description:         '<img style="border-radius: 50%" src="/public/img/yassir_small.jpg" /> Just another personal blog, where I write about python, c++ and other stuff.'
url:                 https://ykarroum.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yassir Karroum
  url:               https://ykarroum.com
  email:             ukarroum17@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
