# Setup
title:               YKarroum
tagline:             'A blog about python, finance and other stuffs'
description:         '<img style="border-radius: 50%" src="/public/img/yassir_small.jpg" /> Just another random blog, where a software engineer talks about python, finance, developpement and other things.'
url:                 http://ykarroum.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yassir Karroum
  url:               http://ykarroum.com
  email:             ukarroum17@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
